- name: Configure and Deploy Web Application
  hosts: all
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
      become: true

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - php
        - mysql-server
        # Add more packages as needed

    - name: Deploy web application files
      copy:
        src: /path/to/local/web/app
        dest: /var/www/html/
      become: true

    # Add more tasks as needed